neutral_words = ["okay", "fine", "average", "normal", "regular", "standard", "typical", "ordinary", "fair", "moderate",
                 "acceptable","you",
                 "usual", "balanced", "adequate", "reasonable", "sufficient", "median", "common", "mild", "neutral",
                 "plain",
                 "simple", "basic", "general", "routine", "consistent", "minimal", "steady", "uniform", "stable",
                 "equal",
                 "constant", "clear", "defined", "fixed", "formal", "official", "central", "local", "global",
                 "regional", "daily",
                 "weekly", "monthly", "yearly", "frequent", "occasional", "periodic", "continuous", "steady",
                 "recurring",
                 "scheduled", "current", "present", "former", "initial", "later", "final", "temporary", "permanent",
                 "ongoing",
                 "some", "many", "few", "several", "multiple", "numerous", "certain", "various", "total", "partial",
                 "equal", "half",
                 "double", "triple", "full", "empty", "low", "high", "medium", "moderate", "small", "large", "short",
                 "long", "tall",
                 "wide", "narrow", "thin", "thick", "heavy", "light", "fast", "slow", "early", "near", "far",
                 "close",
                 "distant", "maximum", "minimum", "active", "inactive", "available", "unavailable", "present", "absent",
                 "visible",
                 "invisible", "open", "closed", "public", "private", "internal", "external", "general", "specific",
                 "valid",
                 "invalid", "working", "functional", "true", "false", "correct", "incorrect", "exact", "approximate",
                 "certain",
                 "uncertain", "possible", "probable", "definite", "indefinite", "logical", "factual", "neutral",
                 "objective",
                 "subjective", "relevant", "irrelevant", "Okay", "Fine", "Average", "Normal", "Usual", "Typical",
                 "Standard", "Ordinary",
                 "Regular", "Moderate", "Stable", "Balanced", "Calm", "Neutral", "Steady", "Even", "Plain", "Flat",
                 "Mild", "Middle",
                 "Equal", "Unchanged", "Constant", "Routine", "Indifferent", "Meh", "Unremarkable", "So-so", "Middling",
                 "Decent",
                 "Manageable", "Acceptable", "Not bad", "Fair", "Passable", "Sufficient", "Mixed", "Level-headed",
                 "Practical",
                 "Content", "Tolerable", "Average-looking", "Moderate-level", "Neutrality", "Middle-ground",
                 "Balanced-out",
                 "Unsure", "Not sure", "Usual state", "Unbiased", "Objective", "Detached", "Impartial", "Dispassionate",
                 "Reserved",
                 "Quiet", "Cool", "Laid-back", "Relaxed", "Casual", "Collected", "Undisturbed", "Nonchalant",
                 "Matter-of-fact",
                 "Even-tempered", "Temperate", "Reasonable", "Clear", "Straightforward", "SimpleOkay", "Fine",
                 "Average", "Normal",
                 "Usual", "Typical", "Standard", "Ordinary", "Regular", "Moderate", "Stable", "Balanced", "Calm",
                 "Neutral",
                 "Steady", "Even", "Plain", "Flat", "Mild", "Middle", "Equal", "Unchanged", "Constant", "Routine",
                 "Indifferent",
                 "Meh", "Unremarkable", "So-so", "Middling", "Decent", "Manageable", "Acceptable", "Not bad", "Fair",
                 "Passable",
                 "Sufficient", "Mixed", "Level-headed", "Practical", "Content", "Tolerable", "Average-looking",
                 "Moderate-level",
                 "Neutrality", "Middle-ground", "Balanced-out", "Unsure", "Not sure", "Usual state", "Unbiased",
                 "Objective",
                 "Detached", "Impartial", "Dispassionate", "Reserved", "Quiet", "Cool", "Laid-back", "Relaxed",
                 "Casual",
                 "Collected", "Undisturbed", "Nonchalant", "Matter-of-fact", "Even-tempered", "Temperate", "Reasonable",
                 "Clear",
                 "Straightforward", "Simple"
                 ]
